// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/docs/internal/cmd"
	"github.com/goforj/docs/internal/docs"
	"github.com/goforj/docs/internal/hello"
	"github.com/goforj/docs/internal/http"
	"github.com/goforj/docs/internal/logger"
	"github.com/goforj/docs/internal/router"
)

// Injectors from wire.go:

// InitializeApplication initializes the application by providing all the dependencies.
func InitializeApplication() (App, error) {
	appLogger := logger.ProvideAppLogger()
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	generateCommand := docs.NewDocsGenerateCommand(appLogger)
	appCommands := cmd.NewAppCommands(helloWorldCmd, generateCommand)
	helloController := hello.NewController(appLogger)
	appRoutes := router.ProvideAppRoutes(helloController)
	v := router.ProvideRoutes(appRoutes)
	server := http.NewServer(appLogger, v)
	serveCmd := http.NewServeCmd(appLogger, server)
	routeListCmd := http.NewRouteListCmd(appLogger, server)
	rootCmd := cmd.NewRootCmd(appCommands, serveCmd, routeListCmd)
	cache := provideLocalCache()
	app := NewApplication(appLogger, rootCmd, cache)
	return app, nil
}
