package cmd

// Code generated by GoForj CLI scaffolder. DO NOT EDIT.
// Add user-defined commands in AppCommands instead.

import (
	"github.com/goforj/docs/internal/http"
)

// RootCmd is the root command for the application.
type RootCmd struct {
	AppCommands // Application-specific commands are registered here

	// goforj component commands
	// http server
	HttpServeCmd       http.ServeCmd                `cmd:"" name:"http:serve" help:"Start the HTTP server"`
	RoutesListCmd      http.RouteListCmd            `cmd:"" name:"route:list" help:"List HTTP routes"`
}

// NewRootCmd creates a new RootCmd with the given commands.
func NewRootCmd(
	appCmds *AppCommands,
	httpServeCmd *http.ServeCmd,
	routesListCmd *http.RouteListCmd,
) *RootCmd {
	return &RootCmd{
		AppCommands:        *appCmds,
		HttpServeCmd:       *httpServeCmd,
		RoutesListCmd:      *routesListCmd,
	}
}
